### ISSUE TITLE
Recursive definition of le and eq in LowerSemilattice and UpperSemilattice

### ISSUE THREAD

**Issue by jyuhuan** [ctongfei/poly-algebra#1]
The `le` method in the trait `LowerSemilattice` is defined using the `eq` method from the super trait `PartialOrder`: 

``` scala
def le(x: X, y: X) = eq(x, inf(x, y))
```

However, in that super trait, `eq` depends on `le`: 

``` scala
def eq(x: X, y: X) = le(x, y) && le(y, x)
```

The two methods depend on each other, resulting in a recursive definition, and could very likely cause runtime errors, consequently.

The same issue is also found in the trait `UpperSemilattice`.

**Comment by ctongfei** [comment]
Resolved by making a semilattice not a PartialOrder. Created an "asPartialOrder" method in a semilattice.
